/*global $*/
$(".pigla").click(function(){
    window.open("https://agarciany.github.io/piglaten/");
});
$(".rockp").click(function(){
    window.open("https://kingaldair.github.io/advanced_rockpaperscissors_startercode/");
});
$(".gifs").click(function(){
    window.open("https://agarciany.github.io/gif/");
});
$(".hagman").click(function(){
    window.open("https://kingaldair.github.io/unit13HangmanStarterCode/");
});
$(".helpingyou").click(function(){
    window.open("https://kingaldair.github.io/helping-you/");
});
$(".didor").click(function(){
    window.open("https://jalvarez2016.github.io/disorderhelper/");
});
$(".mario").click(function(){
    window.open("https://kingaldair.github.io/sidescroll-game/");
});
$(".school").click(function(){
    window.open("https://jalvarez2016.github.io/Compture-science-class/");
});