/*global $*/
$(".pigla").click(function(){
    window.location.assign("https://agarciany.github.io/piglaten/");
});
$(".rockp").click(function(){
    window.location.assign("https://kingaldair.github.io/advanced_rockpaperscissors_startercode/");
});
$(".gifs").click(function(){
    window.location.assign("https://agarciany.github.io/gif/");
});
$(".hagman").click(function(){
    window.location.assign("https://kingaldair.github.io/unit13HangmanStarterCode/");
});
$(".helpingyou").click(function(){
    window.location.assign("https://kingaldair.github.io/helping-you/");
});
$(".child6").click(function(){
    window.location.assign("https://agarciany.github.io/piglaten/");
});
$(".child7").click(function(){
    window.location.assign("https://kingaldair.github.io/sidescroll-game/");
});
$(".child8").click(function(){
    window.location.assign("https://agarciany.github.io/piglaten/");
});